name: 🌟 TreeOM Quantum Sync

on:
  # Запуск при изменении в ветке main
  push:
    branches:
      - main
    paths:
      - "index.html"
      - ".github/workflows/**"
      - ".github/workflows/artifact_sync.json"

  # Регулярный запуск каждые 15 минут
  schedule:
    - cron: "*/15 * * * *"

  # Вручную через интерфейс GitHub Actions
  workflow_dispatch:

jobs:
  sync-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate GuardianFilter
        run: |
          python scripts/validate_filter.py filters/GuardianFilter_OM.json artifact_sync.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync artifacts
        run: |
          python scripts/sync_artifacts.py